### ISSUE TITLE
Transfer all tasks into repository (create new issue for every task)

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#1]
**Tasks (main functionality)**

1. Transfer all tasks into repository (create new issue for every task)
2. Create readme file with basic description of application and its functionality
3. Create main HTML, CSS and JS files
4. Create HTML table with 7x7 squares
5. Populate table with static digits and give them red and black colors
6. Create buttons: “start a test” and “finish a test”
7. Add timer which would start upon clicking “start” button and stops upon clicking “finish” or after 90 sec
8. Add button which would open the modal/dialog window with instructions
9. Add instruction for every step after user starts the test e.g. “please find 25 red”
10. Add pointer and click listener for every square, b) make square slightly change background color upon hover
11. Add logic for square click listener function that would record the correct and incorrect enters (see test rules)
12. Create a function that would push the results into local storage upon end of the test
13. Create results modal/dialog window, which would appear after test ends
14. Add form to collect user information
15. Add “history” button, which would show history of the user results information in new (or same) window e.g. Date, Name, result
16. Add tests

**Tasks (deployment)**

1. Discover free deployment options
2. Add linter, prettier etc.
3. Deploy the app on the remote server, so that it is publicly accessible
4. Set up CI/CD pipeline (write delivery.yaml file)

**Comment by levnikan** [comment]
Cool, we can close this issue! :+1:
